const stages=[
{title:'Power Station',enemy:'Static Slime',icon:'⚡',qs:[
['Which object becomes positively charged after losing electrons?','失去电子后，物体带什么电？',['Negatively charged','Positively charged','Neutral','Magnetic'],1,'Losing electrons leaves more protons, so the object is positively charged.'],
['Like electric charges will…','同种电荷会怎样？',['attract','repel','disappear','become neutral'],1,'Like charges repel; unlike charges attract.'],
['Which material is commonly an electrical insulator?','哪一种材料通常是绝缘体？',['Copper','Iron','Rubber','Aluminium'],2,'Rubber does not allow electric current to flow easily.'],
['A charged ruler attracts tiny paper pieces due to…','带电尺吸引小纸片是由于什么？',['gravity','electrostatic force','friction only','magnetism'],1,'The attraction is caused by electrostatic force.'],
['Which device protects buildings from lightning?','哪一种装置保护建筑物免受雷击？',['Ammeter','Lightning conductor','Voltmeter','Fuse wire'],1,'A lightning conductor provides a safe path for charge to Earth.'],
['BOSS: State the safest action during a thunderstorm.','Boss：雷雨时最安全的做法是什么？',['Stand under a tree','Hold a metal pole','Stay inside a building','Swim'],2,'Stay inside a building and avoid exposed metal objects.'],
['BOSS: Earthing removes excess charge by transferring it to…','Boss：接地把多余电荷传到哪里？',['the Moon','Earth','a battery','a magnet'],1,'Earthing transfers excess electric charge safely to Earth.']]},
{title:'Current River',enemy:'Current Eel',icon:'≈',qs:[
['Electric current is the rate of flow of…','电流是何种粒子的流动率？',['mass','charge','heat','light'],1,'Electric current is the rate of flow of electric charge.'],
['The SI unit of electric current is…','电流的国际单位是？',['volt','ohm','ampere','coulomb'],2,'Current is measured in ampere, A.'],
['Which instrument measures electric current?','哪一种仪器测量电流？',['Voltmeter','Ammeter','Thermometer','Barometer'],1,'An ammeter measures electric current.'],
['An ammeter is connected…','电流表怎样连接？',['in parallel','in series','outside the circuit','to Earth only'],1,'An ammeter must be connected in series.'],
['Conventional current flows from…','传统电流方向从哪里到哪里？',['negative to positive','positive to negative','Earth to battery','bulb to switch only'],1,'Conventional current flows from the positive terminal to the negative terminal.'],
['BOSS: If more charge flows each second, current becomes…','Boss：每秒流过的电荷增加，电流会怎样？',['smaller','larger','zero','unchanged'],1,'More charge per second means a larger current.'],
['BOSS: Which circuit condition allows current to flow?','Boss：哪一种电路状态允许电流流动？',['Open circuit','Complete circuit','Broken wire','Open switch'],1,'Current flows only through a complete circuit.']]},
{title:'Resistance Factory',enemy:'Ohm Golem',icon:'Ω',qs:[
['Voltage is measured using a…','电压使用什么仪器测量？',['ammeter','voltmeter','balance','stopwatch'],1,'A voltmeter measures potential difference.'],
['A voltmeter is connected…','电压表怎样连接？',['in series','in parallel','without wires','to one terminal only'],1,'A voltmeter is connected in parallel across a component.'],
['The SI unit of resistance is…','电阻的国际单位是？',['ampere','volt','ohm','watt'],2,'Resistance is measured in ohm, Ω.'],
['A longer wire usually has… resistance.','较长的电线通常有怎样的电阻？',['lower','higher','zero','no'],1,'A longer wire gives more opposition to current.'],
['A thicker wire usually has… resistance.','较粗的电线通常有怎样的电阻？',['higher','lower','infinite','unchanged'],1,'A thicker wire provides more paths for charge, so resistance is lower.'],
['BOSS: Increasing resistance while voltage stays constant causes current to…','Boss：电压不变而电阻增加，电流会怎样？',['increase','decrease','stay zero forever','double'],1,'Higher resistance reduces current.'],
['BOSS: Which material is a good conductor?','Boss：哪一种材料是良好导体？',['Plastic','Glass','Copper','Rubber'],2,'Copper allows current to flow easily.']]},
{title:'Circuit City',enemy:'Circuit Dragon',icon:'⌁',qs:[
['In a series circuit, current is… at all points.','串联电路中，各处电流怎样？',['different','the same','always zero','unmeasurable'],1,'A series circuit has one path, so current is the same throughout.'],
['If one bulb breaks in a series circuit…','串联电路中一个灯泡坏了会怎样？',['others stay on','all bulbs go off','current increases','battery disappears'],1,'The single path is broken, so all bulbs go off.'],
['A parallel circuit has…','并联电路具有什么？',['one path only','more than one path','no switch','no current'],1,'Parallel circuits provide multiple paths.'],
['If one bulb breaks in a parallel circuit…','并联电路中一个灯泡坏了会怎样？',['all go off','other branches can still work','battery melts','voltage becomes zero everywhere'],1,'Other branches remain complete.'],
['Adding more cells in series generally makes a bulb…','串联增加电池通常使灯泡怎样？',['dimmer','brighter','colder only','magnetic'],1,'More cells provide a larger potential difference.'],
['BOSS: Household wiring uses mainly… circuits.','Boss：家庭电路主要使用哪种连接？',['series','parallel','open','broken'],1,'Parallel wiring lets appliances operate independently.'],
['BOSS: Which circuit gives each bulb a separate path?','Boss：哪种电路让每个灯泡有独立路径？',['Series','Parallel','Open','Short only'],1,'Parallel circuits have separate branches.']]},
{title:'Magnet Fortress',enemy:'Magnetron',icon:'N',qs:[
['Like magnetic poles…','同名磁极会怎样？',['attract','repel','melt','lose mass'],1,'Like poles repel.'],
['Unlike magnetic poles…','异名磁极会怎样？',['repel','attract','become neutral','produce heat only'],1,'Unlike poles attract.'],
['The magnetic field is strongest at the…','磁场在哪里最强？',['centre only','poles','air far away','handle'],1,'Magnetic field lines are most concentrated near the poles.'],
['Which material is attracted strongly by a magnet?','哪一种材料会被磁铁强烈吸引？',['Iron','Plastic','Wood','Glass'],0,'Iron is a magnetic material.'],
['An electromagnet needs…','电磁铁需要什么？',['electric current','sunlight only','water','friction only'],0,'Current in a coil produces a magnetic field.'],
['BOSS: How can an electromagnet be made stronger?','Boss：怎样增强电磁铁？',['Use fewer coil turns','Reduce current','Add more coil turns','Remove the iron core'],2,'More turns produce a stronger magnetic field.'],
['FINAL BOSS: A scrapyard crane uses an electromagnet because it can be…','最终Boss：废铁场起重机使用电磁铁，因为它可以怎样？',['switched on and off','made of plastic','used without current','permanently weak'],0,'The current can be switched on to lift metal and off to release it.']]}
];
const $=id=>document.getElementById(id);
let si=0,qi=0,xp=0,hp=100,correct=0,locked=false,review=[],student='Student',combo=0,bestCombo=0;
function allQuestions(){return stages.reduce((a,s)=>a+s.qs.length,0)}
function buildMap(){const m=$('stageMap');m.innerHTML='';stages.forEach((s,i)=>{const n=document.createElement('div');n.className='stage-node '+(i<si?'done':i===si?'active':'');n.textContent=i+1;m.appendChild(n);if(i<stages.length-1){const l=document.createElement('div');l.className='stage-line';m.appendChild(l)}})}
function render(){locked=false;buildMap();const s=stages[si],q=s.qs[qi];$('hudStage').textContent=si+1;$('hudXp').textContent=xp;$('hudHp').textContent=hp;$('hudCombo').textContent=combo+'×';$('stageLabel').textContent=`STAGE ${si+1}`;$('stageTitle').textContent=s.title;$('counter').textContent=`${qi+1} / ${s.qs.length}`;$('enemyName').textContent=s.enemy;$('enemyAvatar').textContent=s.icon;$('question').textContent=q[0];$('questionZh').textContent=q[1];$('feedback').className='feedback hidden';$('answers').innerHTML='';q[2].forEach((c,i)=>{const b=document.createElement('button');b.textContent=`${String.fromCharCode(65+i)}. ${c}`;b.addEventListener('click',()=>answer(i));$('answers').appendChild(b)});$('playerHpBar').style.width=hp+'%';$('enemyHpBar').style.width=((s.qs.length-qi)/s.qs.length*100)+'%'}
function beep(ok){try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?720:150;if(ok)o.frequency.exponentialRampToValueAtTime(1050,c.currentTime+.18);g.gain.value=.07;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.3);o.stop(c.currentTime+.31)}catch(e){}}
function animateBattle(ok,critical){const p=$('playerFighter'),e=$('enemyFighter'),a=$('arena'),f=$('battleFlash'),fx=$('attackFx'),text=$('impactText');[p,e,a,f].forEach(x=>x.className=x.className.replace(/\s(attack|hit|shake|good|bad)/g,''));if(ok){p.classList.add('attack');e.classList.add('hit');f.classList.add('good');fx.classList.remove('hidden');text.textContent=critical?'CRITICAL HIT!':'SUPER EFFECTIVE!';text.classList.remove('hidden')}else{e.classList.add('attack');p.classList.add('hit');a.classList.add('shake');f.classList.add('bad');text.textContent='MONSTER ATTACK!';text.classList.remove('hidden')}setTimeout(()=>{fx.classList.add('hidden');text.classList.add('hidden');p.classList.remove('attack','hit');e.classList.remove('attack','hit');a.classList.remove('shake');f.classList.remove('good','bad')},700)}
function simpleZh(explain){const rules=[
['positively charged','电子像负号。少了电子，正电就比较多，所以带正电。'],['Like charges repel','同样的两端像两个人互相推开；不同的两端才会靠近。'],['Rubber','橡胶像一堵墙，电流不容易穿过去，所以它是绝缘体。'],['electrostatic force','尺子带电后像有看不见的小手，把轻纸片吸过来。'],['lightning conductor','避雷针给电荷一条安全道路直接去地面。'],['inside a building','雷雨时躲进建筑物，远离树、金属和水最安全。'],['to Earth','地球像一个超大电荷仓库，可以安全接走多余电荷。'],['rate of flow','电流就像水流，单位时间流过的电荷越多，电流越大。'],['ampere','电流用安培 A 表示。看到 current，就想 ampere。'],['ammeter','Ammeter 的 A 对应 Ampere，所以用来测电流。'],['in series','电流表要放在电流必经的路上，所以必须串联。'],['positive terminal','传统电流从电池正极出发，流向负极。'],['larger current','每秒通过的电荷越多，就像水管每秒流更多水，电流更大。'],['complete circuit','电路必须形成完整一圈，电流才有路可走。'],['voltmeter','Voltmeter 的 V 对应 Voltage，所以用来测电压。'],['in parallel','电压表要比较元件两端，所以跨在元件两边并联。'],['ohm','电阻的单位是欧姆，符号是 Ω。'],['longer wire','路越长，电荷碰撞机会越多，所以电阻越大。'],['thicker wire','电线越粗，电荷可走的通道越多，所以电阻越小。'],['reduces current','电阻像路障。路障越多，电流越小。'],['Copper','铜让电流容易通过，所以是良好导体。'],['one path','串联只有一条路，因此每一处流过的是同一个电流。'],['all bulbs go off','串联只有一条路，一处断开，整条路都不能通。'],['multiple paths','并联像多条道路，电流可以分开走。'],['Other branches','并联的一条支路坏了，其他完整支路仍然能工作。'],['larger potential difference','电池增加，推动电荷的力量更大，灯泡通常更亮。'],['independently','家庭电器要各自开关，所以使用并联。'],['Like poles repel','同名磁极互相排斥：N推N，S推S。'],['Unlike poles attract','异名磁极互相吸引：N吸S。'],['near the poles','磁力线在磁极附近最密，所以那里磁力最强。'],['Iron','铁是磁性材料，会被磁铁明显吸引。'],['Current in a coil','电流通过线圈会制造磁场，所以形成电磁铁。'],['More turns','线圈圈数越多，磁场叠加得越强。'],['switched on and off','电磁铁有电才吸，无电就放开，所以方便搬运废铁。']];
for(const [key,value] of rules)if(explain.includes(key))return value;return '先找题目的关键词，再把正确答案和科学概念连接起来。';}
function answer(i){if(locked)return;locked=true;const s=stages[si],q=s.qs[qi],ok=i===q[3];beep(ok);if(ok){correct++;combo++;bestCombo=Math.max(bestCombo,combo);const critical=combo>0&&combo%3===0;xp+=critical?180:100;animateBattle(true,critical);$('feedbackTitle').textContent=critical?'CRITICAL HIT! +180 XP':'SUPER EFFECTIVE! +100 XP'}else{combo=0;hp=Math.max(0,hp-15);animateBattle(false,false);review.push({stage:s.title,question:q[0],questionZh:q[1],chosen:q[2][i],correct:q[2][q[3]],explain:q[4],eli5:simpleZh(q[4])});$('feedbackTitle').textContent='MONSTER ATTACK! -15 HP'}[...$('answers').children].forEach((b,j)=>b.className=j===q[3]?'correct':j===i?'wrong':'dim');$('feedback').className='feedback '+(ok?'good':'bad');$('explanation').textContent=ok?q[4]:`Correct answer: ${q[2][q[3]]}. ${simpleZh(q[4])}`;$('hudXp').textContent=xp;$('hudHp').textContent=hp;$('hudCombo').textContent=combo+'×';$('playerHpBar').style.width=hp+'%'}
function next(){qi++;if(qi>=stages[si].qs.length){si++;qi=0;hp=Math.min(100,hp+25)}if(si>=stages.length)return finish();render()}
function start(){student=$('studentName').value.trim()||'Student';si=0;qi=0;xp=0;hp=100;correct=0;combo=0;bestCombo=0;review=[];$('hudName').textContent=student;$('playerNamePlate').textContent=student.toUpperCase();$('startScreen').classList.add('hidden');$('resultScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');render()}
function finish(){const rank=correct>=32?'SCIENCE MASTER':correct>=25?'GRID GUARDIAN':correct>=18?'SPARK EXPLORER':'ROOKIE';$('gameScreen').classList.add('hidden');$('resultScreen').classList.remove('hidden');$('resultName').textContent=student;$('finalXp').textContent=xp;$('finalCorrect').textContent=`${correct}/${allQuestions()}`;$('finalRank').textContent=rank;$('bestCombo').textContent=bestCombo+'×';$('wrongCount').textContent=review.length+'题';const panel=$('reviewPanel'),list=$('reviewList');if(review.length){panel.classList.remove('hidden');list.innerHTML=review.map((r,i)=>`<article class="review-item"><h4>${i+1}. ${r.question}</h4><p>${r.questionZh}</p><div class="review-answer"><div class="wrong"><b>你的答案</b><br>${r.chosen}</div><div class="right"><b>正确答案</b><br>${r.correct}</div></div><p class="eli5"><b>ELI5 简单解释：</b>${r.eli5}</p></article>`).join('')}else{panel.classList.remove('hidden');list.innerHTML='<article class="review-item"><h4>全对！没有错题需要复习。</h4><p class="eli5">你已经成功掌握本次挑战。</p></article>'}saveRecord(rank)}
function saveRecord(rank){try{const key='scienceMonstersRecords';const records=JSON.parse(localStorage.getItem(key)||'[]');records.unshift({student,date:new Date().toLocaleString(),xp,correct,total:allQuestions(),rank,wrong:review});localStorage.setItem(key,JSON.stringify(records.slice(0,30)))}catch(e){}}
$('startBtn').addEventListener('click',start);$('restartBtn').addEventListener('click',()=>{$('resultScreen').classList.add('hidden');$('startScreen').classList.remove('hidden')});$('nextBtn').addEventListener('click',next);$('studentName').addEventListener('keydown',e=>{if(e.key==='Enter')start()});